added an arc
Fails with:
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/run/media/desperado/smb/daten/eigene_dateien/isl/messtechnik/stossrohr/selfmade/cfd/example_arc.py in <module>()
     80 # output
     81 #print(bmd.format())string = bmd.format()
---> 82 string = bmd.format()
     83 f = open("blockMeshDict", "w")
     84 f.write(string)

/usr/lib/python3.6/site-packages/ofblockmeshdicthelper/__init__.py in format(self)
    410 (
    411 );'''
--> 412 
    413     def format(self):
    414         template = Template(r'''/*--------------------------------*- C++ -*----------------------------------*\

/usr/lib/python3.6/site-packages/ofblockmeshdicthelper/__init__.py in format_edges_section(self)
    349             v.index = i
    350 
--> 351     def format_vertices_section(self):
    352         """format vertices section.
    353         assign_vertexid() should be called before this method, because

/usr/lib/python3.6/site-packages/ofblockmeshdicthelper/__init__.py in format(self, vertices)
    190     def __init__(self, vnames, name, interVertex):
    191         """Initialize ArcEdge instance
--> 192         vnames is the vertex names in order descrived in
    193           http://www.openfoam.org/docs/user/mesh-description.php
    194         # two vertices is needed for Arc

AttributeError: 'str' object has no attribute 'x'